--[[
	BEGOTTEN III: Developed by DETrooper, cash wednesday, gabs & alyousha35
--]]

PLUGIN:SetGlobalAlias("cwStorage")

util.Include("cl_plugin.lua")
util.Include("sv_plugin.lua")
util.Include("sv_hooks.lua")
util.Include("cl_hooks.lua")

cwStorage.containerList = {
	["models/props_wasteland/controlroom_storagecloset001a.mdl"] = {8, "Железный Шкаф"},
	["models/props_wasteland/controlroom_storagecloset001b.mdl"] = {15, "Железный Шкаф"},
	["models/props_wasteland/controlroom_filecabinet001a.mdl"] = {4, "Картотека"},
	["models/props_wasteland/controlroom_filecabinet002a.mdl"] = {8, "Картотека"},
	["models/props_c17/suitcase_passenger_physics.mdl"] = {5, "Чемодан"},
	["models/props_junk/wood_crate001a_damagedmax.mdl"] = {8, "Деревянный Ящик"},
	["models/props_junk/wood_crate001a_damaged.mdl"] = {8, "Деревянный Ящик"},
	["models/props_interiors/furniture_desk01a.mdl"] = {4, "Стол"},
	["models/props_c17/cashregister01a.mdl"] = {4, "Касса"},
	["models/props_c17/furnituredresser001a.mdl"] = {10, "Комод"},
	["models/props_c17/furnituredrawer001a.mdl"] = {8, "Ящик"},
	["models/props_c17/furnituredrawer002a.mdl"] = {4, "Ящик"},
	["models/props_c17/furniturefridge001a.mdl"] = {8, "Холодильник"},
	["models/props_c17/furnituredrawer003a.mdl"] = {8, "Ящик"},
	["models/weapons/w_suitcase_passenger.mdl"] = {5, "Чемодан"},
	["models/props_junk/trashdumpster01a.mdl"] = {15, "Мусорка"},
	["models/props_junk/wood_crate001a.mdl"] = {8, "Деревянный Ящик"},
	["models/props_junk/wood_crate002a.mdl"] = {10, "Деревянный Ящик"},
	["models/items/ammocrate_rockets.mdl"] = {15, "Большой Ящик"},
	["models/props_lab/filecabinet02.mdl"] = {8, "Картотека"},
	["models/items/ammocrate_grenade.mdl"] = {15, "Большой Ящик"},
	["models/props_junk/trashbin01a.mdl"] = {10, "Мусорка"},
	["models/props_c17/suitcase001a.mdl"] = {8, "Чемодан"},
	["models/items/item_item_crate.mdl"] = {4, "Ящик"},
	["models/props_c17/oildrum001.mdl"] = {8, "Бочка"},
	["models/items/ammocrate_smg1.mdl"] = {15, "Большой Ящик"},
	["models/items/ammocrate_ar2.mdl"] = {15, "Большой Ящик"},
	["models/props_junk/cardboard_box001a.mdl"] = {4, "Ящик"},
	["models/props_junk/cardboard_box002a.mdl"] = {4, "Ящик"},
	["models/props_junk/cardboard_box003a.mdl"] = {3, "Ящик"},
	["models/props_wasteland/kitchen_fridge001a.mdl"] = {25, "Холодильник"},
	["models/props_lab/partsbin01.mdl"] = {4, "Почтовый Ящик"},
	["models/props_office/file_cabinet_large_static.mdl"] = {25, "Большая Картотека"},
	["models/props/cs_militia/footlocker01_closed.mdl"] = {15, "Сундук"},
	["models/props_c17/furniturewashingmachine001a.mdl"] = {10, "Стиральная Машинка"},
	["models/props_c17/furniturestove001a.mdl"] = {10, "Печь"},
	["models/props_c17/lockers001a.mdl"] = {17, "Шкаф"},
	["models/props_wasteland/cargo_container01.mdl"] = {1000, "Контейнер"},
	["models/props_c17/briefcase001a.mdl"] = {6, "Сундук"},
	["models/props_combine/breendesk.mdl"] = {10, "Стол"},
	["models/props/cs_militia/crate_extrasmallmill.mdl"] = {15, "Ящик"},
	["models/props/cs_militia/crate_extralargemill.mdl"] = {15, "Ящик"},
	["models/props/cs_militia/crate_stackmill.mdl"] = {15, "Ящик"},
	["models/props/cs_militia/dryer.mdl"] = {10, "Сушилка"},
	["models/props_c17/furniturecupboard001a.mdl"] = {7, "Буфет"},
	["models/props_borealis/bluebarrel001.mdl"] = {10, "Бочка"},
	["models/props_wasteland/kitchen_counter001c.mdl"] = {17, "Кухонный Стол"},
	["models/props_junk/plasticbucket001a.mdl"] = {4, "Ведерко"},
	["models/items/boxmrounds.mdl"] = {5, "Коробка"},
	["models/items/boxsrounds.mdl"] = {3, "Коробка"},
	["models/props/cs_assault/dryer_box.mdl"] = {8, "Ящик"},
	["models/props/cs_assault/dryer_box2.mdl"] = {8, "Ящик"},
	["models/props/cs_assault/washer_box.mdl"] = {8, "Ящик"},
	["models/props/cs_assault/washer_box2.mdl"] = {8, "Ящик"},
	["models/props/cs_assault/box_stack1.mdl"] = {20, "Коробки"},
	["models/props/cs_assault/box_stack2.mdl"] = {20, "Коробки"},
	["models/props/cs_assault/moneypallet_washerdryer.mdl"] = {17, "Коробки"},
	["models/props/cs_militia/stove01.mdl"] = {15, "Печь"},
	["models/props/cs_office/cardboard_box01.mdl"] = {8, "Ящик"},
	["models/props/cs_office/cardboard_box02.mdl"] = {8, "Ящик"},
	["models/props/cs_office/cardboard_box03.mdl"] = {8, "Ящик"},
	["models/props/cs_office/file_cabinet1.mdl"] = {7, "Шкафчик"},
	["models/props/cs_office/file_cabinet1_group.mdl"] = {20, "Шкафчик"},
	["models/props/cs_office/file_cabinet2.mdl"] = {7, "Шкафчик"},
	["models/props/cs_office/file_cabinet3.mdl"] = {7, "Шкафчик"},
	["models/props/de_nuke/crate_extralarge.mdl"] = {200, "Большой Ящик"},
	["models/props/de_nuke/crate_extrasmall.mdl"] = {100, "Ящик"},
	["models/props/de_nuke/crate_large.mdl"] = {150, "Ящик"},
	["models/props/de_nuke/crate_small.mdl"] = {125, "Ящик"},
	["models/props/de_nuke/file_cabinet1_group.mdl"] = {12, "Шкафчик"},
	["models/props/de_prodigy/ammo_can_01.mdl"] = {30, "Военные Ящики"},
	["models/props/de_prodigy/ammo_can_02.mdl"] = {10, "Военные Ящики"},
	["models/props/de_prodigy/ammo_can_03.mdl"] = {60, "Военные Ящики"},
	["models/begotten/misc/lockbox.mdl"] = {50, "Сундук"},
}